version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: box-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: box-backend
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/box?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      # 挂载上传目录，便于调试和持久化
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: box-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: box
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: box-redis
    restart: always
    ports:
      - "6379:6379"