/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetForm: typeof import('./components/asset/AssetForm.vue')['default']
    AssetForm1: typeof import('./components/asset/AssetForm1.vue')['default']
    AssetForm2: typeof import('./components/asset/AssetForm2.vue')['default']
    AssetList: typeof import('./components/asset/AssetList.vue')['default']
    AssetName: typeof import('./components/asset/assetName/AssetName.vue')['default']
    AssetNameForm: typeof import('./components/asset/assetName/AssetNameForm.vue')['default']
    AssetNameForm1: typeof import('./components/asset/assetName/AssetNameForm1.vue')['default']
    AssetNameList: typeof import('./components/asset/assetName/AssetNameList.vue')['default']
    AssetNameModal1: typeof import('./components/asset/assetName/AssetNameModal1.vue')['default']
    AssetNameSearch: typeof import('./components/asset/assetName/AssetNameSearch.vue')['default']
    AssetNameTable: typeof import('./components/asset/assetName/AssetNameTable.vue')['default']
    AssetSearch: typeof import('./components/asset/AssetSearch.vue')['default']
    AssetStats: typeof import('./components/dashboard/components/AssetStats.vue')['default']
    AssetTable: typeof import('./components/asset/AssetTable.vue')['default']
    AuthModals: typeof import('./components/auth/AuthModals.vue')['default']
    BaseActions: typeof import('./components/base/BaseActions.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseDialog: typeof import('./components/base/BaseDialog.vue')['default']
    BaseEmptyState: typeof import('./components/base/BaseEmptyState.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseMultiSelect: typeof import('./components/base/BaseMultiSelect.vue')['default']
    BaseNotice: typeof import('./components/base/BaseNotice.vue')['default']
    BasePagination: typeof import('./components/base/BasePagination.vue')['default']
    BasePaginationBar: typeof import('./components/base/BasePaginationBar.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    BaseStatCard: typeof import('./components/base/BaseStatCard.vue')['default']
    BaseTable: typeof import('./components/base/BaseTable.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    EmptyState: typeof import('./components/base/EmptyState.vue')['default']
    FitnessForm: typeof import('./components/fitness/FitnessForm.vue')['default']
    FitnessList: typeof import('./components/fitness/FitnessList.vue')['default']
    FitnessSearch: typeof import('./components/fitness/FitnessSearch.vue')['default']
    FitnessStats: typeof import('./components/dashboard/components/FitnessStats.vue')['default']
    FitnessTable: typeof import('./components/fitness/FitnessTable.vue')['default']
    LoginModal: typeof import('./components/auth/LoginModal.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    Notification: typeof import('./components/base/Notification.vue')['default']
    PaginationBar: typeof import('./components/base/PaginationBar.vue')['default']
    Profile: typeof import('./components/layout/Profile.vue')['default']
    RegisterModal: typeof import('./components/auth/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/asset/SearchPanel.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SkeletonCard: typeof import('./components/base/SkeletonCard.vue')['default']
    UserMenuAuthenticated: typeof import('./components/layout/UserMenuAuthenticated.vue')['default']
    UserMenuGuest: typeof import('./components/layout/UserMenuGuest.vue')['default']
  }
}
