/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetForm: typeof import('./components/asset/AssetForm.vue')['default']
    AssetList: typeof import('./components/asset/AssetList.vue')['default']
    AssetName: typeof import('./components/asset/assetName/AssetName.vue')['default']
    AssetNameForm: typeof import('./components/asset/assetName/AssetNameForm.vue')['default']
    AssetNameList: typeof import('./components/asset/assetName/AssetNameList.vue')['default']
    AssetNameSearch: typeof import('./components/asset/assetName/AssetNameSearch.vue')['default']
    AssetNameTable: typeof import('./components/asset/assetName/AssetNameTable.vue')['default']
    AssetScanAddModal: typeof import('./components/asset/AssetScanAddModal.vue')['default']
    AssetSearch: typeof import('./components/asset/AssetSearch.vue')['default']
    AssetStats: typeof import('./components/dashboard/components/AssetStats.vue')['default']
    AssetTable: typeof import('./components/asset/AssetTable.vue')['default']
    AuthModals: typeof import('./components/auth/AuthModals.vue')['default']
    BaseActions: typeof import('./components/base/BaseActions.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCalendar: typeof import('./components/base/BaseCalendar.vue')['default']
    BaseDateInput: typeof import('./components/base/BaseDateInput.vue')['default']
    BaseDialog: typeof import('./components/base/BaseDialog.vue')['default']
    BaseEmptyState: typeof import('./components/base/BaseEmptyState.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseNotice: typeof import('./components/base/BaseNotice.vue')['default']
    BasePagination: typeof import('./components/base/BasePagination.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    BaseStatCard: typeof import('./components/base/BaseStatCard.vue')['default']
    BaseTable: typeof import('./components/base/BaseTable.vue')['default']
    BaseTimeSelector: typeof import('./components/base/BaseTimeSelector.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    FitnessForm: typeof import('./components/fitness/FitnessForm.vue')['default']
    FitnessList: typeof import('./components/fitness/FitnessList.vue')['default']
    FitnessSearch: typeof import('./components/fitness/FitnessSearch.vue')['default']
    FitnessStats: typeof import('./components/dashboard/components/FitnessStats.vue')['default']
    FitnessTable: typeof import('./components/fitness/FitnessTable.vue')['default']
    LoginModal: typeof import('./components/auth/LoginModal.vue')['default']
    Profile: typeof import('./components/layout/Profile.vue')['default']
    RecognizedAssetsTable: typeof import('./components/asset/RecognizedAssetsTable.vue')['default']
    RegisterModal: typeof import('./components/auth/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    UserMenuAuthenticated: typeof import('./components/layout/UserMenuAuthenticated.vue')['default']
    UserMenuGuest: typeof import('./components/layout/UserMenuGuest.vue')['default']
  }
}
