/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetForm: typeof import('./components/asset/AssetForm.vue')['default']
    AssetList: typeof import('./components/asset/AssetList.vue')['default']
    AssetModal: typeof import('./components/asset/AssetModal.vue')['default']
    AssetNameForm: typeof import('./components/asset/AssetNameForm.vue')['default']
    AssetNamesList: typeof import('./components/asset/AssetNamesList.vue')['default']
    AssetNamesModal: typeof import('./components/asset/AssetNamesModal.vue')['default']
    AssetNamesTable: typeof import('./components/asset/AssetNamesTable.vue')['default']
    AssetStats: typeof import('./components/dashboard/components/AssetStats.vue')['default']
    AssetTable: typeof import('./components/asset/AssetTable.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FitnessForm: typeof import('./components/fitness/FitnessForm.vue')['default']
    FitnessList: typeof import('./components/fitness/FitnessList.vue')['default']
    FitnessModal: typeof import('./components/fitness/FitnessModal.vue')['default']
    FitnessStats: typeof import('./components/dashboard/components/FitnessStats.vue')['default']
    FitnessTable: typeof import('./components/fitness/FitnessTable.vue')['default']
    GlobalModals: typeof import('./components/GlobalModals.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ModalHeader: typeof import('./components/asset/ModalHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    Notification: typeof import('./components/Notification.vue')['default']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PaginationBar: typeof import('./components/common/PaginationBar.vue')['default']
    RecordActions: typeof import('./components/common/RecordActions.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/asset/SearchPanel.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SkeletonCard: typeof import('./components/common/SkeletonCard.vue')['default']
    UserMenuAuthenticated: typeof import('./components/user/UserMenuAuthenticated.vue')['default']
    UserMenuGuest: typeof import('./components/user/UserMenuGuest.vue')['default']
  }
}
