server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/box?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write-numbers-as-strings: true
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

jwt:
  secret: RjFk8V2p9X7mN3qL5tYzA4wQ1cB6vE0sH8uD2xG4nJ7bK9mP3rT5

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.esin.box.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志配置
logging:
  level:
    root: INFO
    com.esin.box: DEBUG
    com.esin.box.mapper: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.security: DEBUG
    # PaddleOCR相关日志
    com.esin.box.service.ocr: DEBUG

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# 应用配置
app:
  upload:
    # 临时文件目录（用于OCR识别）
    temp-dir: ${java.io.tmpdir}/box/asset-images
    # 文件上传保存路径
    path: ${user.home}/box-uploads
    # 允许的文件类型
    allowed-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/gif
      - image/bmp
      - image/webp
    # 文件大小限制（字节）
    max-size: 10485760  # 10MB
  ocr:
    paddle:
      # Python解释器路径
      python-path: /Users/ESin/Scripts/paddle_env_py310/bin/python
      # PaddleOCR Python脚本路径 - 请确认这个路径是否正确
      script-path: /Users/ESin/Scripts/paddle_ocr_processor.py
      # 支持的语言
      language: ch
      # OCR识别超时时间（秒）
      timeout: 60
      # 是否保留识别后的临时文件（调试用）
      keep-temp-files: true  # 改为true来调试
      # 最大并发处理数
      max-concurrent: 3
      # 输出文件临时目录
      output-temp-dir: ${java.io.tmpdir}/box/paddle-ocr-output