server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/box?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write-numbers-as-strings: true
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

jwt:
  secret: RjFk8V2p9X7mN3qL5tYzA4wQ1cB6vE0sH8uD2xG4nJ7bK9mP3rT5

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.esin.box.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志配置
logging:
  level:
    root: INFO
    com.esin.box: DEBUG
    com.esin.box.mapper: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.security: DEBUG
    # OCR相关日志
    net.sourceforge.tess4j: INFO

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# 应用配置
app:
  upload:
    # 临时文件目录（用于OCR识别）
    temp-dir: ${java.io.tmpdir}/box/asset-images
    # 文件上传保存路径
    path: ${user.home}/box-uploads
    # 允许的文件类型
    allowed-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/gif
      - image/bmp
      - image/webp
    # 文件大小限制（字节）
    max-size: 10485760  # 10MB
  ocr:
    tesseract:
      # Tesseract 数据路径配置
      # Mac mini 上的路径（根据安装方式选择）：
      # - Homebrew Intel: /usr/local/share/tessdata
      # - Homebrew Apple Silicon: /opt/homebrew/share/tessdata
      # - MacPorts: /opt/local/share/tessdata
      # 自动检测路径（在启动类中实现）
      data-path: /opt/homebrew/share/tessdata
      # 备用路径（Apple Silicon）
      data-path-alt: /usr/local/share/tessdata
      # 语言包：中文简体+英文
      language: chi_sim+eng
      # OCR 引擎模式
      # 0 = 仅传统Tesseract
      # 1 = 仅神经网络LSTM
      # 2 = 传统+LSTM（默认）
      # 3 = 基于可用性自动选择
      ocr-engine-mode: 1
      # 页面分割模式
      # 1 = 带方向和脚本检测的自动页面分割
      # 3 = 全自动页面分割，但没有方向和脚本检测（默认）
      # 6 = 统一的文本块
      # 11 = 稀疏文本，按任意顺序查找尽可能多的文本
      page-seg-mode: 3
      # DPI设置（提高识别精度）
      dpi: 300
      # 是否保留识别后的临时文件（调试用）
      keep-temp-files: false
      # 识别超时时间（秒）
      timeout: 30