server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/box?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write-numbers-as-strings: true

jwt:
  secret: RjFk8V2p9X7mN3qL5tYzA4wQ1cB6vE0sH8uD2xG4nJ7bK9mP3rT5

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.box.login.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志配置
logging:
  level:
    root: INFO
    com.box.login: DEBUG
    com.box.login.mapper: DEBUG
    com.box.login.mapper.FitnessRecordMapper: TRACE
    org.springframework.data.redis: INFO
    org.springframework.security: DEBUG

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
